import { ApiEvent, Event } from "./types";

export const mockApiEvents: ApiEvent[] = [
  {
    id: 3431,
    title: "Immatrikuleringsfest",
    description: "Fest for faddergruppene etter Immatrikulering",
    cover:
      "https://thumbor-staging.abakus.no/e2YXPMIrT1nhb1up-1_odgl4444=/0x500/Arrangementsheader_imywpML.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/0OzNk07khooTgPlIP4xf3a096PQ=/0x50/filters:blur(20)/Arrangementsheader_imywpML.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Studentersamfundet",
    startTime: "2023-08-14T19:00:00Z",
    endTime: "2023-08-14T21:59:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/fBUez-UmmP-84qcBGPNU90HBfjo=/500x500/smart/Arrangementsheader_imywpML.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3448,
    title: "Ny-i-trondheim!",
    description: "TBA",
    cover:
      "https://thumbor-staging.abakus.no/OKwRYNiUONI6_M5MQMRwekLZciA=/0x500/ezgif.comwebptopng.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/0cncJHbbd8dbhupYK0nNGspiKVo=/0x50/filters:blur(20)/ezgif.comwebptopng.png",
    eventType: "other",
    eventStatusType: "TBA",
    location: "TBA",
    startTime: "2023-08-15T13:15:00Z",
    endTime: "2023-08-15T15:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/aQoOxA8clVOvV3T7r5J_8vXTpjE=/500x500/smart/ezgif.comwebptopng.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3433,
    title: "Grilling i Høyskoleparken",
    description: "Grilling for faddergrupper",
    cover:
      "https://thumbor-staging.abakus.no/eJKpRRaZlFY3dyNVrE3RBS1SUWg=/0x500/Arrangementsheader_UurygdX.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/TeB1cEiGvVUwxkodHSTxlWVcZ3E=/0x50/filters:blur(20)/Arrangementsheader_UurygdX.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Høyskoleparken",
    startTime: "2023-08-15T14:00:00Z",
    endTime: "2023-08-15T18:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/Bzl7N1ychBPuTMsf6UH3AgJywak=/500x500/smart/Arrangementsheader_UurygdX.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3435,
    title: "Ops, jeg kom feil!",
    description: "Temafest for faddergrupper",
    cover:
      "https://thumbor-staging.abakus.no/zlRyYcXEnW_2niUNA3Snx68UpIM=/0x500/Arrangementsheader_qrqzqD6.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/G6FYmcggjRABRsROqWUNyLvTxLo=/0x50/filters:blur(20)/Arrangementsheader_qrqzqD6.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Fire Fine",
    startTime: "2023-08-16T19:00:00Z",
    endTime: "2023-08-16T21:59:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/GnqGC827amptuQCa0Rg4yYuAKVQ=/500x500/smart/Arrangementsheader_qrqzqD6.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3436,
    title: "Jente- og guttevors!",
    description: "Jente og guttegrupper i FP",
    cover:
      "https://thumbor-staging.abakus.no/yT0O1GJUAkMoGMP4DOlAdp3XxUU=/0x500/Arrangementsheader_51PopIH.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/ZYmXIHPbl3uQEFvSq_5ZAG9QN1E=/0x50/filters:blur(20)/Arrangementsheader_51PopIH.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "TBA",
    startTime: "2023-08-18T15:00:00Z",
    endTime: "2023-08-18T21:59:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/Df_rfT9VORs3ChoymaiEoWxQ-BI=/500x500/smart/Arrangementsheader_51PopIH.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3439,
    title: "Beerolympics",
    description: "Beerolympics i FP på Festningen",
    cover:
      "https://thumbor-staging.abakus.no/ywvj3rApec2Ih8Q5edWH179HdRM=/0x500/Arrangementsheader_Zgc1FF3.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/NtGJZlzqckFfTA-s3OefT_ItEtQ=/0x50/filters:blur(20)/Arrangementsheader_Zgc1FF3.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Festningsparken",
    startTime: "2023-08-19T10:00:00Z",
    endTime: "2023-08-19T12:30:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/lTla5csNuTwFMiBMN5x7oc4es2Y=/500x500/smart/Arrangementsheader_Zgc1FF3.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3432,
    title: "Leilighet til leilighet",
    description: "Mandag 21. august er det tid for leilighet til leilighet <3",
    cover:
      "https://thumbor-staging.abakus.no/3VC4icgITYeouEVblQQmRIBGwfg=/0x500/Arrangementsheader_9yKIMte.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/W_0DzrzZzWAbkjamMYtB4Mu0wmQ=/0x50/filters:blur(20)/Arrangementsheader_9yKIMte.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Keeeeeege leiligheter",
    startTime: "2023-08-21T15:30:00Z",
    endTime: "2023-08-21T21:59:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/isLYm_vlSicbay7QVnL8sb2QMnw=/500x500/smart/Arrangementsheader_9yKIMte.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3434,
    title: "A3-dagen",
    description: "A3 dagen! Bli kjent med hva Abakus har å by på",
    cover:
      "https://thumbor-staging.abakus.no/CIs0cswxdAlJaYA0TLiBSKYxrps=/0x500/Arrangementsheader_RZlPFjJ.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/yPwsctNpqlkU7zMBMWWUPH5eKLw=/0x50/filters:blur(20)/Arrangementsheader_RZlPFjJ.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Abakus, Realfagbygget",
    startTime: "2023-08-22T15:00:00Z",
    endTime: "2023-08-22T17:30:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/HzYFaEDd1e5-fP6yoagrPARudg8=/500x500/smart/Arrangementsheader_RZlPFjJ.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3437,
    title: "Hippieløp",
    description: "Hippieløp <3 love you guys",
    cover:
      "https://thumbor-staging.abakus.no/xJ89Ew7Rcqo4-e7aod56NCh4brA=/0x500/Arrangementsheader_IKsabik.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/xU210GhgkydPgJC0NRTM8u_btNE=/0x50/filters:blur(20)/Arrangementsheader_IKsabik.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "hele t-town",
    startTime: "2023-08-23T15:00:00Z",
    endTime: "2023-08-23T18:30:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/yrBIiWDraghoSQ8oC4TmndIKv0s=/500x500/smart/Arrangementsheader_IKsabik.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3438,
    title: "Rebus",
    description: "Bli kjent med alt og alle på spenstig rebus",
    cover:
      "https://thumbor-staging.abakus.no/kCBM2S370sA6iD4GNyDDr5Gi-Go=/0x500/Arrangementsheader_8wo04tQ.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/rpLdideSmDy79xz2ZyhdEElkuMg=/0x50/filters:blur(20)/Arrangementsheader_8wo04tQ.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Glazzhaugen",
    startTime: "2023-08-24T15:30:00Z",
    endTime: "2023-08-24T18:15:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/-wa5B99C-3-05440IftTLE2thkE=/500x500/smart/Arrangementsheader_8wo04tQ.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3440,
    title: "Silent Disco på Havet",
    description:
      "Hold på bølgene, det er på tide å slippe løs din indre danser på en helt ny måte - nemlig gjennom en Silent Disco på Havet!",
    cover:
      "https://thumbor-staging.abakus.no/eEFeciBXhIgPaFjf3rUGie8FS8Q=/0x500/Arrangementsheader_PqZnoaA.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/OHZIqw1ifFo5RJZhwAP5PG28Izo=/0x50/filters:blur(20)/Arrangementsheader_PqZnoaA.png",
    eventType: "event",
    eventStatusType: "NORMAL",
    location: "Havet",
    startTime: "2023-08-25T19:00:00Z",
    endTime: "2023-08-26T00:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/tGvbT5HHnIuIbdr_xc3MD7K7meI=/500x500/smart/Arrangementsheader_PqZnoaA.png",
    totalCapacity: 293,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: true,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3441,
    title: "Skattejakt og piratfest",
    description:
      "Heis flagget og hev anker. En morsom skattejakt på Skansen venter på deg og faddergruppa di!",
    cover:
      "https://thumbor-staging.abakus.no/ws2mbbf-QUUOEx9swxm3bE4ei2s=/0x500/Arrangementsheader_QcuTwnz.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/N6VmQjws9Au56VINiOyc0L3n8Sw=/0x50/filters:blur(20)/Arrangementsheader_QcuTwnz.png",
    eventType: "event",
    eventStatusType: "OPEN",
    location: "Skansen",
    startTime: "2023-08-26T10:00:00Z",
    endTime: "2023-08-26T13:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/KQPrJHoY1L2pkgrQFwqmAGRyCnM=/500x500/smart/Arrangementsheader_QcuTwnz.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3442,
    title: "Lunsj og Datakamtrening!",
    description:
      "Bryt ut av fadderperiode-bobblen og bli med oss på en hyggelig lunsj mens vi tar en oppsummering av de siste to ukene.",
    cover:
      "https://thumbor-staging.abakus.no/q5LsNcVizSDnZuv4R8hc7qHgjWA=/0x500/Arrangementsheader_coNuAW6.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/LcLWoylYnYEsVxWZJqO_VBFiJZQ=/0x50/filters:blur(20)/Arrangementsheader_coNuAW6.png",
    eventType: "event",
    eventStatusType: "TBA",
    location: "TBA",
    startTime: "2023-08-27T10:00:00Z",
    endTime: "2023-08-27T12:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/6mttJJu4GI3kMAF-KwabF41ng-g=/500x500/smart/Arrangementsheader_coNuAW6.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
  {
    id: 3382,
    title: "Immatrikuleringsball",
    description: "Immatrikuleringsball 2023",
    cover:
      "https://thumbor-staging.abakus.no/i6QI1O5wY8PBYVblzW5fxtnZYhQ=/0x500/Arrangementsheader.png",
    coverPlaceholder:
      "https://thumbor-staging.abakus.no/mwUOaOZVMnmgmKOB2cd85zDewiI=/0x50/filters:blur(20)/Arrangementsheader.png",
    eventType: "event",
    eventStatusType: "TBA",
    location: "TBA",
    startTime: "2023-09-03T17:00:00Z",
    endTime: "2023-09-03T22:00:00Z",
    thumbnail:
      "https://thumbor-staging.abakus.no/IStFDrekKc5kfvRaiZ0cC1yj7ZA=/500x500/smart/Arrangementsheader.png",
    totalCapacity: 0,
    company: null,
    registrationCount: 0,
    tags: [],
    activationTime: null,
    isAdmitted: false,
    survey: null,
    isPriced: false,
    canEditUsers: [],
    canViewGroups: [],
    canEditGroups: [],
    requireAuth: false,
  },
];

export const mockEvents: Event[] = mockApiEvents.map((apiEvent) => {
  const event: any = { ...apiEvent };
  event.startTime = new Date(apiEvent.startTime);
  event.endTime = new Date(apiEvent.endTime);
  return { ...event };
});
